# BTN1
set_property PACKAGE_PIN J5 [get_ports clk]    
set_property IOSTANDARD LVCMOS33 [get_ports clk]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]
set_property CLOCK_BUFFER_TYPE NONE [get_ports clk]

# BTN0
set_property PACKAGE_PIN J2 [get_ports reset]  
set_property IOSTANDARD LVCMOS33 [get_ports reset]

# LEDS
set_property PACKAGE_PIN A4 [get_ports {Outport1[7]}]
set_property PACKAGE_PIN B4 [get_ports {Outport1[6]}]
set_property PACKAGE_PIN A3 [get_ports {Outport1[5]}]
set_property PACKAGE_PIN B3 [get_ports {Outport1[4]}]
set_property PACKAGE_PIN A2 [get_ports {Outport1[3]}]
set_property PACKAGE_PIN B2 [get_ports {Outport1[2]}]
set_property PACKAGE_PIN C3 [get_ports {Outport1[1]}]
set_property PACKAGE_PIN E6 [get_ports {Outport1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport1[0]}]

set_property PACKAGE_PIN E5 [get_ports {Outport0[7]}]
set_property PACKAGE_PIN E3 [get_ports {Outport0[6]}]
set_property PACKAGE_PIN E2 [get_ports {Outport0[5]}]
set_property PACKAGE_PIN E1 [get_ports {Outport0[4]}]
set_property PACKAGE_PIN F2 [get_ports {Outport0[3]}]
set_property PACKAGE_PIN F1 [get_ports {Outport0[2]}]
set_property PACKAGE_PIN G2 [get_ports {Outport0[1]}]
set_property PACKAGE_PIN G1 [get_ports {Outport0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport0[0]}]

# SWITCHES
set_property PACKAGE_PIN K1 [get_ports {Inport1[7]}]
set_property PACKAGE_PIN K2 [get_ports {Inport1[6]}]
set_property PACKAGE_PIN L1 [get_ports {Inport1[5]}]
set_property PACKAGE_PIN M1 [get_ports {Inport1[4]}]
set_property PACKAGE_PIN M2 [get_ports {Inport1[3]}]
set_property PACKAGE_PIN N1 [get_ports {Inport1[2]}]
set_property PACKAGE_PIN N2 [get_ports {Inport1[1]}]
set_property PACKAGE_PIN P1 [get_ports {Inport1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport1[0]}]

set_property PACKAGE_PIN P2 [get_ports {Inport0[7]}]
set_property PACKAGE_PIN R1 [get_ports {Inport0[6]}]
set_property PACKAGE_PIN R2 [get_ports {Inport0[5]}]
set_property PACKAGE_PIN T1 [get_ports {Inport0[4]}]
set_property PACKAGE_PIN T2 [get_ports {Inport0[3]}]
set_property PACKAGE_PIN U1 [get_ports {Inport0[2]}]
set_property PACKAGE_PIN U2 [get_ports {Inport0[1]}]
set_property PACKAGE_PIN V2 [get_ports {Inport0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport0[0]}]
