# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Chirag/Winter24/EGR426/Projects/Project3_Mar21/cpu/cpu.srcs/sources_1/ip/cpuram/cpuram.xci
# IP: The module: 'cpuram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Chirag/Winter24/EGR426/Projects/Project3_Mar21/cpu/cpu.gen/sources_1/ip/cpuram/cpuram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpuram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Chirag/Winter24/EGR426/Projects/Project3_Mar21/cpu/cpu.srcs/sources_1/ip/cpuram/cpuram.xci
# IP: The module: 'cpuram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Chirag/Winter24/EGR426/Projects/Project3_Mar21/cpu/cpu.gen/sources_1/ip/cpuram/cpuram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpuram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
